version: '3'
services:
  app:
    image: object-detection
    # command: tail -f /dev/null
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config/config.docker.yaml:/app/config/config.yaml
    env_file:
      - .env.docker
    environment:
      - CUDA_VISIBLE_DEVICES=1,2
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    