version: '3.8'
services:
  app:
    # image: object-detection
    build:
      context: .
      dockerfile: Dockerfile
    # If need to bash into container, uncomment the following line - then run `docker exec -it <object-detection-app-1> /bin/bash`
    # command: tail -f /dev/null
    volumes:
      - ./data:/app/data
    env_file:
      - .env.docker
    ports:
      - 8013:8013
    environment:
      - DEBUG=1
    networks:
      - rtx-net
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
networks:
  rtx-net:
    name: rtx-net
    driver: bridge
    external: true
    