version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "rtx-controller:1.0.0"
    # If need to bash into container, uncomment the following line - then run `docker exec -it <container> /bin/bash`
    # command: tail -f /dev/null
    restart: always
    env_file:
      - .env.docker
    networks:
      - rtx-net
    environment:
      - DEBUG=1

networks:
  rtx-net:
    name: rtx-net
    driver: bridge
    external: true