FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive 

RUN mkdir -p /app/data
WORKDIR /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 iputils-ping net-tools iproute2  -y

COPY stream_video.docker.sh .
CMD ["./stream_video.docker.sh"]
# ENTRYPOINT [ "/bin/bash" ]